#!/bin/sh

set -eu

repo_root=$(git rev-parse --show-toplevel)
runtime_root=${OPENSPEC_RUNTIME_DIR:-"$repo_root/.scratch/openspec-runtime"}

mkdir -p "$runtime_root/home" "$runtime_root/xdg" "$runtime_root/tmp"

HOME="$runtime_root/home" \
XDG_CONFIG_HOME="$runtime_root/xdg" \
TMPDIR="$runtime_root/tmp" \
OPENSPEC_TELEMETRY=0 \
exec openspec "$@"
